/**
 * pnpm report:coverage — data/reports/coverage.md: which companies are crawled (and how), which are not
 * (and why), and the discovery candidates waiting for review. Regenerated by `pnpm import:cse`.
 */
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { CompaniesFile, type Company } from "@rekiya/shared";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../../../..");

interface Candidate {
  url: string;
  score: number;
  evidence: string[];
  title?: string;
}
interface DomainResult {
  domain: string;
  companies: string[];
  candidates: Candidate[];
  errors: string[];
}

const how = (c: Company) => (c.adapter === "custom" ? `custom: ${String(c.adapterConfig.kind)}` : c.adapter);
const esc = (s: string) => s.replace(/\|/g, "\\|");

export function renderCoverage(companies: Company[], discovery: DomainResult[] | null): string {
  const L: string[] = ["# Crawl coverage", ""];
  const crawled = companies.filter((c) => c.status === "ready" && c.active);
  const inactive = companies.filter((c) => !c.active);
  const pending = companies.filter((c) => c.active && c.status === "needs-adapter");
  const discovery_ = companies.filter((c) => c.active && c.status === "needs-discovery");
  const research = companies.filter((c) => c.active && c.status === "needs-research");

  L.push("| | Companies |", "|---|---|");
  L.push(`| Crawled (ready + active) | ${crawled.length} |`);
  L.push(`| Careers page known, not crawled yet (needs-adapter) | ${pending.length} |`);
  L.push(`| Deliberately not crawled (active: false) | ${inactive.length} |`);
  L.push(`| Website known, careers page unknown (needs-discovery) | ${discovery_.length} |`);
  L.push(`| No website known (needs-research) | ${research.length} |`);
  L.push(`| **Total** | **${companies.length}** |`, "");

  L.push("## Crawled", "", "| Company | Method | Notes |", "|---|---|---|");
  for (const c of crawled) L.push(`| ${esc(c.name)} | ${how(c)} | ${esc(c.notes ?? "")} |`);
  L.push("");

  L.push("## Not crawled — and why", "", "| Company | Reason |", "|---|---|");
  for (const c of [...inactive, ...pending])
    L.push(`| ${esc(c.name)} | ${esc(c.notes ?? (c.active ? "Careers page known; adapter not built yet." : "Inactive."))} |`);
  L.push("");

  if (discovery) {
    const withCands = discovery.filter((d) => d.candidates.length);
    L.push(
      "## Discovery candidates awaiting review",
      "",
      "Found by `pnpm discover` (homepage links, sitemaps, common paths). **Nothing here is crawled** until a maintainer",
      "copies an approved URL into `careersUrl` and picks an adapter (see README → Add a company).",
      "",
      "| Companies | Best candidate | Score | Evidence |",
      "|---|---|---|---|",
    );
    for (const d of withCands) {
      const best = d.candidates[0]!;
      L.push(`| ${esc(d.companies.join(", "))} | ${best.url} | ${best.score} | ${esc(best.evidence.slice(0, 3).join("; "))} |`);
    }
    const unreachable = discovery.filter((d) => !d.candidates.length);
    L.push("", `${unreachable.length} domains gave no candidate (unreachable, blocked by robots.txt, or no careers link).`, "");
  }
  return L.join("\n") + "\n";
}

function main(): void {
  const companies = CompaniesFile.parse(JSON.parse(readFileSync(resolve(ROOT, "data/companies.json"), "utf8")));
  const dPath = resolve(ROOT, "data/discovery-candidates.json");
  const discovery = existsSync(dPath) ? (JSON.parse(readFileSync(dPath, "utf8")) as { domains: DomainResult[] }).domains : null;
  writeFileSync(resolve(ROOT, "data/reports/coverage.md"), renderCoverage(companies, discovery));
  console.log("✓ Wrote data/reports/coverage.md");
}

if (process.argv[1] && fileURLToPath(import.meta.url) === resolve(process.argv[1])) main();
